import { Activity, AlertTriangle, Database, Gauge, Waves } from "lucide-react"

import { DataBadge } from "@/components/ui/DataBadge"
import { GlassCard } from "@/components/ui/GlassCard"
import { PhiPill } from "@/components/ui/PhiPill"

const cards = [
  {
    title: "Network Health",
    icon: Gauge,
    value: "72%",
    caption: "segments in PHI 0-1",
    badge: <PhiPill value={2} />
  },
  {
    title: "Active Incidents",
    icon: AlertTriangle,
    value: "7",
    caption: "open operational events",
    badge: <DataBadge label="S3" value="2" tone="red" />
  },
  {
    title: "Tank Fleet",
    icon: Database,
    value: "61%",
    caption: "average headroom",
    badge: <DataBadge label="risk" value="3 tanks" tone="yellow" />
  },
  {
    title: "Water Availability",
    icon: Waves,
    value: "-0.8σ",
    caption: "GRACE anomaly",
    badge: <DataBadge label="30d" value="watch" tone="teal" />
  }
]

export default function MissionControlPage() {
  return (
    <div className="mx-auto grid max-w-7xl gap-5">
      <section className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="font-[var(--font-jetbrains)] text-xs uppercase tracking-[0.18em] text-[var(--acea-cyan)]">
            Mission Control
          </p>
          <h1 className="mt-2 font-[var(--font-unbounded)] text-3xl font-semibold tracking-normal text-[var(--text-hi)]">
            Ciociaria live operations
          </h1>
        </div>
        <div className="flex flex-wrap gap-2">
          <DataBadge label="backend" value="HF Space" />
          <DataBadge label="pilot" value="Frosinone" tone="teal" />
          <DataBadge label="mode" value="digital twin" tone="yellow" />
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {cards.map((card) => {
          const Icon = card.icon
          return (
            <GlassCard key={card.title} className="p-4">
              <div className="flex items-center justify-between">
                <div className="grid h-10 w-10 place-items-center rounded-md border border-[var(--glass-stroke)] bg-white/[0.04]">
                  <Icon className="h-5 w-5 text-[var(--acea-cyan)]" />
                </div>
                {card.badge}
              </div>
              <div className="mt-6 font-[var(--font-unbounded)] text-3xl font-semibold tracking-normal">{card.value}</div>
              <div className="mt-1 text-sm text-[var(--text-md)]">{card.title}</div>
              <div className="mt-4 text-xs text-[var(--text-lo)]">{card.caption}</div>
            </GlassCard>
          )
        })}
      </section>

      <section className="grid gap-4 xl:grid-cols-[1.4fr_0.8fr]">
        <GlassCard className="p-4">
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h2 className="font-[var(--font-unbounded)] text-lg tracking-normal">Daily Digest</h2>
              <p className="mt-1 text-sm text-[var(--text-md)]">Generated by the audited Regolo agent run.</p>
            </div>
            <DataBadge label="today" value="ready" />
          </div>
          <div className="grid gap-3">
            {[
              "Frosinone: 3 red segments overnight, concentrated around DMA-3.",
              "Tank TK-03 shows a persistent negative mass-balance residual.",
              "No control parameter is applied without operator approval."
            ].map((item) => (
              <div key={item} className="flex items-start gap-3 rounded-md border border-white/10 bg-white/[0.03] p-3 text-sm text-[var(--text-md)]">
                <Activity className="mt-0.5 h-4 w-4 shrink-0 text-[var(--acea-teal)]" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </GlassCard>

        <GlassCard className="p-4">
          <h2 className="font-[var(--font-unbounded)] text-lg tracking-normal">AI Act Gate</h2>
          <div className="mt-4 grid gap-3 text-sm text-[var(--text-md)]">
            {[
              ["LLM calls", "audit row required"],
              ["Control recs", "operator approval"],
              ["Infrastructure", "digital twin only"],
              ["Brick router", "chat/search only"]
            ].map(([label, value]) => (
              <div key={label} className="flex items-center justify-between border-b border-white/10 pb-2 last:border-b-0">
                <span>{label}</span>
                <span className="font-[var(--font-jetbrains)] text-xs text-[var(--acea-ice)]">{value}</span>
              </div>
            ))}
          </div>
        </GlassCard>
      </section>
    </div>
  )
}
